version: "3"
services:
  bot:
    image: rkrohk/gobot:latest
    env_file: "./.env.gobot"
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ~/mongo/data:/data/db

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
