version: "3"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile_dev
    env_file: "./.env"
    command: /bin/sh -c "while sleep 1000; do :; done"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
