version: "3"
services:
  bot:
    image: rkrohk/gobot:latest
    env_file: "./.env"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes: ~/mongo/data:/data/db
