apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongo-pvc
      containers:
      - name: mongo

        image: mongo:latest
        volumeMounts:
          - mountPath: /data/db
            name: mongodata

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
