apiVersion: apps/v1
kind: Deployment
metadata:
  name: es01
spec:
  selector:
    matchLabels:
      app: es01
  template:
    metadata:
      labels:
        app: es01
    spec:
      volumes:
        - name: data01
          persistentVolumeClaim:
            claimName: data01
      containers:
      - name: es01
        image: rkrohk/elasticsearch
        env:
        - name: discovery.type
          value: single-node
        - name: node.name
          value: es01
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 9200
