apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nltk-data
spec:
  resources:
    requests:
      storage: 50M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatbotapi-data
spec:
  resources:
    requests:
      storage: 200M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
